### ISSUE TITLE
Error í Gagnagrunni

### ISSUE THREAD

**Issue by Snojo** [hgop/syllabus-2017#18]
Ég ákvað að gera kóðann minn barebone til að reyna að fá tenginguna rétta.

```
function getClient() {
    return new Client({
        host: my_postgres_container,
        user: admin,
        password: admin,
        database: hgop
    });
}
```

skilar alltaf villu hjá mér þegar docker-compose up er búinn að runna í smá stund... 

outputtið sem ég fæ

```
Starting day4_my_postgres_container_1 ... 
Starting day4_my_postgres_container_1 ... done
Recreating day4_my_page_counter_app_1 ... 
Recreating day4_my_page_counter_app_1 ... done
Attaching to day4_my_postgres_container_1, day4_my_page_counter_app_1
my_postgres_container_1  | 2017-11-30 22:18:17.200 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
my_postgres_container_1  | 2017-11-30 22:18:17.200 UTC [1] LOG:  listening on IPv6 address "::", port 5432
my_postgres_container_1  | 2017-11-30 22:18:17.203 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
my_postgres_container_1  | 2017-11-30 22:18:17.220 UTC [23] LOG:  database system was shut down at 2017-11-30 22:10:21 UTC
my_postgres_container_1  | 2017-11-30 22:18:17.319 UTC [1] LOG:  database system is ready to accept connections
my_page_counter_app_1    | Server running on 3000
my_page_counter_app_1    | /code/database.js:5
my_page_counter_app_1    |         host: my_postgres_container,
my_page_counter_app_1    |               ^
my_page_counter_app_1    | 
my_page_counter_app_1    | ReferenceError: my_postgres_container is not defined
my_page_counter_app_1    |     at getClient (/code/database.js:5:15)
my_page_counter_app_1    |     at Timeout.initialize [as _onTimeout] (/code/database.js:13:18)
my_page_counter_app_1    |     at ontimeout (timers.js:475:11)
my_page_counter_app_1    |     at tryOnTimeout (timers.js:310:5)
my_page_counter_app_1    |     at Timer.listOnTimeout (timers.js:270:5)
day4_my_page_counter_app_1 exited with code 1

```

Einhverjar hugmyndir?

**Comment by Fanneyyy** [comment]
`my_postgres_container` og aðrir strengir þurfa að hafa gæsalappir, þ.e. `host: 'my_postgres_container'` 😄

**Comment by Snojo** [comment]
*facepalm* takk
